import { ref, watch, onMounted, onUnmounted } from 'vue'

export type ThemeType = 'light' | 'dark' | 'system'

export const useTheme = () => {
    // 1. Initialize State
    const currentTheme = ref<ThemeType>('system')
    let mediaQuery: MediaQueryList | null = null

    // 2. Helper to get system preference
    const getSystemTheme = () => {
        if (typeof window === 'undefined') return 'light'
        return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
    }

    // 3. Core Logic: Apply classes to <html>
    const applyTheme = (theme: ThemeType) => {
        if (typeof window === 'undefined') return

        const isDark = theme === 'dark' || (theme === 'system' && getSystemTheme() === 'dark')
        
        if (isDark) {
            document.documentElement.classList.add('dark')
        } else {
            document.documentElement.classList.remove('dark')
        }

        // Persist user intent
        if (theme === 'system') {
            window.localStorage.removeItem('softtuuls-theme')
        } else {
            window.localStorage.setItem('softtuuls-theme', theme)
        }
    }

    // 4. Handle System Theme Changes (Event Listener)
    const handleSystemChange = () => {
        if (currentTheme.value === 'system') {
            applyTheme('system')
        }
    }

    // Actions
    const setTheme = (theme: ThemeType) => {
        currentTheme.value = theme
        applyTheme(theme)
    }

    const nextTheme = () => {
        const cycle: Record<ThemeType, ThemeType> = {
            'light': 'dark',
            'dark': 'system',
            'system': 'light'
        }
        setTheme(cycle[currentTheme.value])
    }

    // Lifecycle: Hydration and Events
    onMounted(() => {
        // Read initial state generated by anti-FOUC script
        const savedTheme = window.localStorage.getItem('softtuuls-theme') as ThemeType
        if (savedTheme === 'light' || savedTheme === 'dark') {
            currentTheme.value = savedTheme
            // Re-apply to ensure consistency just in case
            applyTheme(savedTheme)
        }

        // Attach system listener
        mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
        mediaQuery.addEventListener('change', handleSystemChange)
    })

    onUnmounted(() => {
        if (mediaQuery) {
            mediaQuery.removeEventListener('change', handleSystemChange)
        }
    })

    return {
        currentTheme,
        setTheme,
        nextTheme
    }
}
